name: Lint and test

env:
  GITHUB_PASSWORD: ${{secrets.GITHUB_TOKEN}}

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # the package.json purposely contains some invalid characters for templating
      # so temporarily set it to something valid to run yarn commands
      - run: |
          cd {{cookiecutter.project_name}}
          npm pkg set 'name'='testing'
          npm pkg set 'version'='0.0.1'
          npm pkg set 'license'='MIT'
          yarn
          yarn lint
          yarn test
          yarn build
